version: '3'
services:
  app:
    image: repocket
    build: .
    environment:
    - DISPLAY=novnc:0.0
    depends_on:
    - novnc
    networks:
    - x11
    volumes:
    - config:/app/.config
  novnc:
    image: psharkey/novnc:latest
    ports:
    - 3000:8080
    networks:
    - x11
volumes:
  config:
networks:
  x11:
